/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.customannotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Documented								
@Inherited							
@Target(ElementType.METHOD)							
@Retention(RetentionPolicy.RUNTIME)		
public @interface MethodInfo {
	
	String author() default "Akash";
	String date();
	int revision() default 1;
	String comments();
}
